app/models.py
from . import login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    id = user.get("user_id")
    return int(id)

class User(UserMixin):
    user = {
        "user_id": 1,
        "username": "SPG",
        "password": "w3w3"
    }
    user_id = user.get('user_id')
    username = user.get('username')
    password = user.get('password')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,PasswordField, BooleanField
from wtforms.validators import Required, Email, EqualTo

class SignupForm(FlaskForm):
    firstname = StringField('Firstname',validators=[Required()])
    lastname = StringField('Lastname', validators=[Required()])
    username = StringField('Username', validators=[Required()])
    email = StringField('Email', validators=[Required])
    password = PasswordField('Password',validators=[Required()])
    confirmpass = PasswordField('Confirm password', validators=[Required(),EqualTo('Password',message="Your passwords do not match!")])
    submit = SubmitField('Submit', validators=[Required()])

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    remember = BooleanField('Remember me?')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap =Bootstrap()


def create_app(config_name):
    # Initializing application
    app = Flask(__name__)

    # Setting up configuration
    app.config.from_object(config_options[config_name])

    # Initialize Flask Extensions
    bootstrap.init_app(app)
    login_manager.init_app(app)

    # Register Blueprints
    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Setting config

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, flash
from . import main
from .forms import SignupForm, LoginForm
from flask_login import login_required, login_user
from ..models import User

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/signup', methods=["GET","POST"])
def sign_up():
    form = SignupForm()

    if form.validate_on_submit():
        flash("Your Sign Up was Successful!")
        return redirect(url_for('main.login'))
    return render_template('signup.html', form=form)

@main.route('/login', methods=["GET","POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        # if form.username.data == User.username:
        #     user_id = User.user_id
        #     login_user(user_id)
        #     flash("You Log In was Successful!")
        return redirect(url_for('main.index'))
    return render_template('login.html', form=form)

@main.route('/profile/user')
def profile():
    return render_template('profile.html')

@main.route('/posts')
def display_all_posts():
    return render_template('allposts.html')

@main.route('/post/post_id')
def post():
    return render_template('post.html')

@main.route('/profile/user/edit')
def edit_profile():
    return render_template('editprofile.html')

app/templates/allposts.html
<link rel="stylesheet" href="../static/styles.css">
{% extends 'base.html' %}
{% block content %}
    
    <div class="container">
        <h1>Latest Posts</h1>
        <div class="row">
            
            <!-- Posts go here -->
            <div class="col-md-8">
                <div class="posts">
                    <div class="card mb-3">
                        <img src="../static/profile_pic.jpg" class="card-img-top" alt="..." style="height:250px;">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <!-- Moment js goes here -->
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div> 
                </div>

                <div class="posts">
                    <div class="card mb-3">
                        <img src="../static/profile_pic.jpg" class="card-img-top" alt="..." style="height:250px;">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <!-- Moment js goes here -->
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div> 
                </div>

                <div class="posts">
                    <div class="card mb-3">
                        <img src="../static/profile_pic.jpg" class="card-img-top" alt="..." style="height:250px;">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <!-- Moment js goes here -->
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div> 
                </div>
            </div>
            

            <!-- Sidebar goes here -->

            <aside class="col-md-4">
                <div class="card" style="width: 18rem; margin-bottom: 25px;">
                    <div class="card-header">
                        Stacks
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fab fa-python"></i> Python</li>
                        <li class="list-group-item"><i class="fab fa-java"></i> Java</li>
                        <li class="list-group-item"><i class="fab fa-js"></i> JavaScript</li>
                        <li class="list-group-item"><i class="fab fa-cuttlefish"></i> C</li>
                        <li class="list-group-item"><i class="fab fa-php"></i> PHP</li>
                    </ul>
                </div>

                <div class="card" style="width: 18rem;">
                    <div class="card-header">
                        Frameworks
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fab fa-angular"></i> Angular</li>
                        <li class="list-group-item"><i class="fab fa-bootstrap"></i> Bootstrap</li>
                        <li class="list-group-item"><i class="fab fa-vuejs"></i> Vue</li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>

    <!-- Navbar section goes here -->
    {% block navbar %}
      {% include 'navbar.html' %}
    {% endblock %}
        
    {% block content %}

    {% endblock %}

  <script src="https://code.jquery.com/jquery-3.4.0.slim.js" integrity="sha256-milezx5lakrZu0OP9b2QWFy1ft/UEUK6NH1Jqz8hUhQ=" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/createpost.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

app/templates/editprofile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <form action="POST">
            <label for="bio">Update Bio</label>
            <br>
            <input type="text" name="Bio">
            <br>
            <label for="stacks">Update Stacks</label>
            <br>
            <input type="text" name="Stacks">
        </form>
    </div>
</div>
{% endblock %}

app/templates/index.html
<link rel="stylesheet" href="../static/styles.css">
{% extends 'base.html' %}

{% block content %}
    
    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to Dev&lt;/log&gt;...</h1>
            <h4>A social site for developers</h4>
            <small><strong>Not registered yet?</strong> click the register button below</small>
            <div class="container">
                <div class="row">
                        <a class="btn btn-primary" href="{{ url_for('main.sign_up') }}">Sign Up</a>
                </div>
            </div>


            
        </div>

    </div>

    <footer class="footer bg bg-dark">
        <div class="container">
            <p style="color:bisque; text-align: center;">Copyright &copy; James, Simon and Mohammed</p>
        </div>
    </footer>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card" style="margin-top: 25px; margin-bottom: 25px; width:25rem;">
                    <div class="card-header">
                        <h3>Log In</h3>
                    </div>
    
                    <div class="card-body">
                        {{wtf.quick_form(form)}}
                    </div>
                </div> 
            </div>
            <div class="col-md-4"></div>
        </div> 
    </div>
{% endblock %}

app/templates/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Dev&lt;/log&gt;</a>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.display_all_posts') }}">Posts <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Stack<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="height: 25px;">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="height: 35px;">Search</button>
            </form>
            
            <ul class="navbar-nav mt-2 mt-lg-0">
                <!-- Sign Up -->
                <li class="nav-item active" style="padding-left:15px;">
                    <a href="{{ url_for( 'main.sign_up') }}" style="text-decoration: none; color: white;"><i class="fas fa-user-plus" style="color: white;"></i> Sign Up</a>
                </li>
                <!-- Login -->
                <li class="nav-item active" style="padding-left:15px;">
                    <a href="{{ url_for( 'main.login') }}" style="text-decoration: none; color: white;"><i class="fas fa-sign-in-alt" style="color: white;"></i> Login</a>
                </li>
                
                <!-- Profile Pic -->
                <a href=" {{ url_for('main.profile') }} "><img src="../static/profile_pic.jpg" alt="prof_pic" style="border-radius: 50%; width: 30px; height: 30px; margin-right: 5px; margin-left: 15px; margin-top: 0; margin-bottom:0;"></a>

            </ul>
        </div>
      </nav>

{% endblock %}

app/templates/post.html
<link rel="stylesheet" href="../static/styles.css">
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <!-- Post Title goes somewhere here? -->
        <h1>Post Title</h1>
        <div class="row">

            <!-- Posts go here -->
            <div class="col-md-8">
                <div class="posts">

                    <!-- Post image goes here if any, use Jinja if to evaluate if true -->
                    <img src="../static/profile_pic.jpg" class="card-img-top img-fluid" alt="Responsive image" style="height:250px; margin-bottom: 25px;">

                    <div class="card mb-3">
                        <!-- Post content goes here -->
                        <div class="card-body">
                            <h5 class="card-title">Post title</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <!-- Moment js goes here -->
                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>
                    </div> 
                </div>
            </div>

            <!-- Side bar goes here -->
            <aside class="col-md-4">
                <div class="card" style="width: 18rem; margin-bottom: 25px;">
                    <div class="card-header">
                        Stacks
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fab fa-python"></i> Python</li>
                        <li class="list-group-item"><i class="fab fa-java"></i> Java</li>
                        <li class="list-group-item"><i class="fab fa-js"></i> JavaScript</li>
                        <li class="list-group-item"><i class="fab fa-cuttlefish"></i> C</li>
                        <li class="list-group-item"><i class="fab fa-php"></i> PHP</li>
                    </ul>
                </div>

                <div class="card" style="width: 18rem;">
                    <div class="card-header">
                        Frameworks
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fab fa-angular"></i> Angular</li>
                        <li class="list-group-item"><i class="fab fa-bootstrap"></i> Bootstrap</li>
                        <li class="list-group-item"><i class="fab fa-vuejs"></i> Vue</li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
{% endblock %}

app/templates/profile.html
<link rel="stylesheet" href="../static/styles.css">
{% extends 'base.html' %}
{% block content %}
<div style="padding-top: 25px;">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4" style>
                <div class="card">
                    <div class="card-header">
                        <div style="text-align: center;">

                                    

                                    <!-- Profile pic goes here -->
                                    <img src="../static/profile_pic.jpg" alt="profile_pic" style="border-radius: 50%; width: 150px; height: 150px;">
                                    <!-- Username goes here -->
                                    <h5 class="card-title">Username</h5>

                                    <!-- Toggle profile picture here -->
                                    <a class="toggle btn btn-primary" style="margin-bottom: 15px;"><i class="fas fa-upload"></i> Upload Profile Picture</a>

                                    <!-- Upload profile pic here -->
                                    <form method="post" enctype ="multipart/form-data" class="upload">
                                    <div class="custom-file">
                                            <label class="custom-file-label" for="inputGroupFile01">Upload Picture</label>
                                        <input type="file" name="photo" class="custom-file-input" id="inputGroupFile01" required>
                                    </div>
                                    <input class="btn btn-success" type="submit">
                                    </form>

                                
                                {% block script %}
                                    <script type="text/javascript">
                                        $(document).ready(function(){
                                            $(".toggle").click(function(){
                                                $(".upload").toggle();
                                            });
                                        });
                                    </script>
                                {% endblock %}
                        </div>
                    </div>

                    <div class="card-body">
                        <!-- Bio goes here -->
                        <div style="text-align: center;">
                            <h5 class="card-title text-center" style="text-align: center;">Bio</h5>
                            <p>Insert brief description about yourself</p>
                        </div>

                        <!-- Description goes here -->
                        <div style="text-align: center;">
                            <h5 class="card-title text-center">Stack</h5>
                            <p>Insert brief description about your stack</p>
                        </div>
                        
                        <a style="text-align: center;" class="btn btn-success" href="{{ url_for('main.edit_profile') }}">Edit Profile</a>
                    </div>


                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card" style="margin-top: 25px; margin-bottom: 25px; width:25rem;">
                    <div class="card-header">
                        <h3>Sign Up</h3>
                    </div>
    
                    <div class="card-body">
                        {{wtf.quick_form(form)}}
                    </div>
                </div> 
            </div>
            <div class="col-md-4"></div>
        </div> 
    </div>


{% endblock %}